codecov:
  require_ci_to_pass: false
  token: null  # Will use GitHub token or repository token
  disable_default_path_fixes: false

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        # For data packages, we don't expect high code coverage
        target: 0%
        threshold: 0%
        base: auto
        if_ci_failed: success  # Don't fail if CI has issues
    patch:
      default:
        target: 0%
        threshold: 0%
        base: auto
        if_ci_failed: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false  # Don't require head for uploads

# For R packages, we typically ignore these directories
ignore:
  - "tests/**/*"
  - "inst/**/*"
  - "man/**/*"
  - "vignettes/**/*"
  - "data/**/*"
  - "data-raw/**/*"