codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        # For data packages, we don't expect high code coverage
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 0%
        threshold: 0%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# For R packages, we typically ignore these directories
ignore:
  - "tests/**/*"
  - "inst/**/*"
  - "man/**/*"
  - "vignettes/**/*"
  - "data/**/*"
  - "data-raw/**/*"