# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )

          # Generate coverage report
          print(cov)

          # Save coverage percentage for the badge
          percent <- covr::percent_coverage(cov)
          cat("\n====================================\n")
          cat("TOTAL CODE COVERAGE:", round(percent, 2), "%\n")
          cat("====================================\n\n")

          # Save coverage report as artifact
          covr::to_cobertura(cov, filename = "coverage.xml")

          # Also create an HTML report
          covr::report(cov, file = "coverage-report.html", browse = FALSE)
        shell: Rscript {0}

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: |
            coverage.xml
            coverage-report.html

      # Only attempt Codecov upload if token exists
      - name: Upload to Codecov
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        continue-on-error: true